DO NOT MERGE this is for GH pages when enabled
dapr/sig-api pull request #10
Opened 2023-08-21 09:15 UTC by salaboy

This PR adds the Swagger UI to be public when GH pages are enabled on this repository.

2023-08-21 16:49 UTC, artursouza requested changes

2023-08-21 16:49 UTC, artursouza commented on index.html
> +<!DOCTYPE html>
I fixed the permissions to enable this. Please, move this to a dir called "www" or something similar. I need to merge this, to configure the pages website. I don't recommend doing it in the root folder.

2023-08-22 12:28 UTC, salaboy commented on index.html
> +<!DOCTYPE html>
moved to "www"

2023-08-22 12:31 UTC, salaboy commented on index.html
> +<!DOCTYPE html>
done

2023-08-22 15:11 UTC, yaron2 approved these changes

2023-08-22 15:11 UTC, merged